// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ElLoading: typeof import('element-plus/es')['ElLoading']
  const ElM: typeof import('element-plus/es')['ElM']
  const ElMESS: typeof import('element-plus/es')['ElMESS']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
}
